### ISSUE TITLE
using other useEffect will cause multiple call of event handlers like onCreated

### ISSUE THREAD

**Issue by tomcosk** [giovanesantossilva/react-leaflet-draft#3]
I am using websockets using useEffect and also one useEffect for load some markers, polylines and also shapes into map when compoent mounts. When DraftControl call onCreated, it calls it 5 times in my case. When I comment out my useEffects, then it is working as expected.  The same happens for other event handlers as well.

I also tried to wrap it to parent component which has useEffect hooks and send props into child component with only mapContainer and DraftControl but it did not help.
Is there any solution for that?

I need websockets and also I need data on load.

Thanks.

**Comment by giovanesantossilva** [comment]
**Hi, I replicated your scenario here and the problem actually occurs, I will try to release a version fixing this problem and improving onCreate by the end of the afternoon, thanks!**
