### ISSUE TITLE
Support for custom text and labels of the draw controls

### ISSUE THREAD

**Issue by manuelpoelzl** [giovanesantossilva/react-leaflet-draft#5]
Hi,

would it be possible to get support for custom text and labels of the draw controls, so we can specify our own?
This is already possible with leaflet itself like this:
```js
L.drawLocal = {
      draw: {
        toolbar: {
          actions: {
            title: 'Cancel - your text-',
            text: '- your text-'
          },
          finish: {
            title: '- your text-',
            text: '- your text-'
          },
          undo: {
            title: '- your text-',
            text: '- your text-'
          },
          buttons: {
            polyline: '- your text-',
            polygon: '- your text-',
            rectangle: '- your text-',
            circle: '- your text-',
            marker: '- your text-',
            circlemarker: '- your text-'
          }
}
```

Maybe there is some way to make this work with EditControl of this library, since the structure is rather similar:
```jsx
<EditControl
   position='topright'
   draw={{rectangle: false}}/>
```

My idea would be, that the draw property of the EditControl can take another ```toolbar``` property, which essentially mirrors the object above and enables us to specify our own texts for the controls.

**Comment by giovanesantossilva** [comment]
Fixed in react-leaflet-draft version 1.2.0!

Thank you very much for the opportunity to improve.
