### ISSUE TITLE
Making properties of the draft control optional

### ISSUE THREAD

**Issue by manuelpoelzl** [giovanesantossilva/react-leaflet-draft#6]
Hi!

Thanks for the implementation of #5! The translations work really well!

However, during the implementation of the translations I found another thing that could be optimized, this is why I'm creating this issue.
In combination with TypeScript, the DraftControl requires me to add all available properties:
![required properties](https://user-images.githubusercontent.com/46539758/217654759-a78bf44d-e306-431a-a121-ef66f6a86fd7.png)

It would be great if only properties that are definitely needed by the control are mandatory and all other ones are optional.
For example, lets assume I've a map which has editing disabled in the draft control, then all callbacks for edit will become useless, but as it is now, they would be required nevertheless. So making these properites optional would be really great, so we can only use the props we actually need.

**Comment by giovanesantossilva** [comment]
Thanks for the feedback, I'll check it out!

**Comment by manuelpoelzl** [comment]
Great thanks!

**Comment by giovanesantossilva** [comment]
Fixed in react-leaflet-draft version 1.2.1!

Thank you very much for the opportunity to improve.
