### ISSUE TITLE
No context provided: useLeafletContext() can only be used in a descendant of <MapContainer> with @react-leaflet/core ^2.1.0

### ISSUE THREAD

**Issue by joeyparis** [giovanesantossilva/react-leaflet-draft#7]
I believe the plugin needs to migrate to useMap() instead of useLeafletContext() for @react-leaflet@^2.1.0

**Comment by giovanesantossilva** [comment]
Hello, I'm already checking and updating the library to work on react-leaflet version 4, currently it only works for react-leaflet version 3.
I'll do an update in the next few days!

What's your stack and plugins versions?

**Comment by ocni-dtu** [comment]
Running into the same problem.
My stack is:

```json
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-leaflet": "^4.2.1",
    "react-leaflet-draft": "^1.2.1",
```

**Comment by giovanesantossilva** [comment]
Hello, I just published a new version of the library compatible with react-leaflet version 4, if you can verify that it is working correctly. if there is still a problem open a new issue here please, thank you!
